### ISSUE TITLE
VPN disconnects on upload during speedtest with trojan connection. Any solution?

### ISSUE THREAD

**Issue by shizong888** [eycorsican/ileaf#41]
Hi @eycorsican 

When connected to trojan servers everything is working fine for regular browsing, but when running a speed test, the connection drops on upload. I believe this is due to exceeding the 15mb memory limit in NetworkExtension. 

Is there any way to resolve this issue? Connecting to the same trojan server using ShadowRocket and running the speed test doesn't disconnect on upload, so I'm assuming they have some sort of memory management in place to stop the network extension from reaching the 15mb hard limit.

So I guess I can sum it up with the following questions: 

1. Is there any way I can configure the trojan connection to use less memory?
2. Is there any way to monitor the memory using Memory Pressure Events and stop the extension from exceeding the 15mb limit before it cuts off?

I would appreciate any help resolving this issue as, although it only really happens during a speed test, this could also happen when uploading/downloading large files causing the connection to drop.

Thanks and look forward to hearing from you!

**Comment by eycorsican** [comment]
There's a discussion [here](https://github.com/eycorsican/leaf/discussions/108), I strongly suggest to try the openssl build, and try various tunable options in openssl. In the early versions of leaf there's also a [native TLS](https://github.com/sfackler/rust-native-tls) implementation which uses the security-framework, it was removed because of an unknown blocking issue and the lack of ALPN support, but it's also worth a try.

For memory monitoring on iOS, there's an [API](https://developer.apple.com/documentation/os/3191911-os_proc_available_memory) on iOS 13.0+.

**Comment by shizong888** [comment]
Thanks for the quick response @eycorsican 

Looks like the dev version is working a lot better with openssl on iOS. We just tested a trojan connection on speedtest and the peak memory usage was down to 11mb peak on upload. We'll do a little more testing and see what settings are optimal for ENDPOINT_TCP_CONCURRENCY and DIRECT_TCP_CONCURRENCY. 

So far, even with ENDPOINT_TCP_CONCURRENCY set to the default, it's maxing out our internet connection on the speedtest and everything is running well. So I'm assuming not much change is needed, maybe just bump it up to 60 to stay on the safe side.

Thanks again for the great project, look forward to seeing support for more protocols in future and to see where the project goes. It's been a complete game changer for us!
